run:
  go: '1.19'

linters-settings:
  gofumpt:
    module-path: github.com/tamj0rd2/sudoku-solver-hack

linters:
  enable:
    - godot
    - goconst
    - gofumpt
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - bodyclose
